### PR TITLE
Added production compose file

### PR DESCRIPTION
**Pull request by patrikulus**
Docker compose file for production server deployment.

## Description
As in title.

## Where should the reviewer start?
Check if app is working on production - this compose is specific for deployment server, there's nothing much to review here

## Motivation and context
I't required for CD #4 

## How has this been tested?
Production env was created from this compose file.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] CI/CD

### CODE REVIEW

**Comment by patrikulus** [comment]
Related with #4

**Comment by WTobor** [comment]
@KrystianKolad - please make review

**Comment by KrystianKolad** [comment]
What is the ASPNETCORE_ENVIRONMENT value? Because you need to add connectionstrong to db if its other than "Docker"

**Comment by patrikulus** [comment]
app.env on the server looks like:
ASPNETCORE_ENVIRONMENT=Production
SQLCONNSTR_DefaultConnection=[production connection string]
and it overrides the default connection string in appsettings.json ;)

**Pull request merged**
